{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swauth\/swautherror\/systemerror(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/SwAuth\/documentation\/SwAuth\/SwAuthError\/systemError(error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A system error occurred."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"SwAuthError.systemError(error:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6SwAuth0aB5ErrorO06systemC0yACs0C0_p_tcACmF","modules":[{"name":"SwAuth"}]},"hierarchy":{"paths":[["doc:\/\/SwAuth\/documentation\/SwAuth","doc:\/\/SwAuth\/documentation\/SwAuth\/SwAuthError"]]},"references":{"doc://SwAuth/documentation/SwAuth":{"role":"collection","title":"SwAuth","abstract":[],"identifier":"doc:\/\/SwAuth\/documentation\/SwAuth","kind":"symbol","type":"topic","url":"\/documentation\/swauth"},"doc://SwAuth/documentation/SwAuth/SwAuthError":{"role":"symbol","title":"SwAuthError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwAuthError"}],"abstract":[{"type":"codeVoice","code":"SwAuthError"},{"type":"text","text":" is the error type that is thrown by methods in this library."}],"identifier":"doc:\/\/SwAuth\/documentation\/SwAuth\/SwAuthError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwAuthError"}],"url":"\/documentation\/swauth\/swautherror"},"doc://SwAuth/documentation/SwAuth/SwAuthError/systemError(error:)":{"role":"symbol","title":"SwAuthError.systemError(error:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A system error occurred."}],"identifier":"doc:\/\/SwAuth\/documentation\/SwAuth\/SwAuthError\/systemError(error:)","kind":"symbol","type":"topic","url":"\/documentation\/swauth\/swautherror\/systemerror(error:)"}}}